# Generated by Django 6.0.2 on 2026-02-17 18:27

from django.db import migrations, models


def transfer_priority_to_importance(apps, schema_editor):
    Todo = apps.get_model("todos", "Todo")

    for todo in Todo.objects.all():
        if hasattr(todo, "priority") and todo.priority is not None:
            mapping = {1: "Low", 2: "Medium", 3: "High"}
            todo.importance = mapping[todo.priority]


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_gowishuser_todo_owner_wishlist_wish"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="importance",
            field=models.CharField(
                blank=True,
                choices=[("Low", "Low"), ("Medium", "Medium"), ("High", "High")],
                null=True,
            ),
        ),
        migrations.RunPython(
            transfer_priority_to_importance,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="todo",
            name="priority",
        ),
    ]
